# Generated by Django 4.0 on 2021-12-13 10:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_pic', models.ImageField(upload_to='profilepic/')),
                ('name', models.CharField(blank=True, max_length=70)),
                ('email', models.EmailField(max_length=254)),
                ('bio', models.CharField(max_length=400)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
            ],
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projectimage', models.ImageField(null=True, upload_to='projectimage')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('link', models.CharField(max_length=150)),
                ('profile', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='aceinitiative.profile')),
            ],
        ),
    ]
