# Generated by Django 4.0 on 2021-12-13 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aceinitiative', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Projects',
            new_name='Project',
        ),
    ]
